import 'violation.dart';

/// Discriminated union of fix strategies.
sealed class Fix {
  const Fix({required this.violation});

  final Violation violation;

  Map<String, dynamic> toJson();
}

/// A fix that can be applied deterministically without AI.
final class AutoFix extends Fix {
  const AutoFix({
    required super.violation,
    required this.replacement,
    required this.description,
  });

  final String replacement;
  final String description;

  @override
  Map<String, dynamic> toJson() => {
        'type': 'auto',
        'violation': violation.toJson(),
        'replacement': replacement,
        'description': description,
      };
}

/// A fix generated by Claude AI.
final class AiFix extends Fix {
  const AiFix({
    required super.violation,
    required this.replacement,
    required this.suggestedFix,
  });

  final String replacement;
  final String suggestedFix;

  @override
  Map<String, dynamic> toJson() => {
        'type': 'ai',
        'violation': violation.toJson(),
        'replacement': replacement,
        'suggestedFix': suggestedFix,
      };
}

/// A violation that requires manual intervention.
final class ManualFix extends Fix {
  const ManualFix({
    required super.violation,
    required this.guidance,
  });

  final String guidance;

  @override
  Map<String, dynamic> toJson() => {
        'type': 'manual',
        'violation': violation.toJson(),
        'guidance': guidance,
      };
}
